{{- if .Values.initJobs}}
  {{- range $initJobs, $job := $.Values.initJobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{$.Release.Name}}"
  labels:
    app.kubernetes.io/managed-by: {{$.Release.Service | quote }}
    app.kubernetes.io/instance: {{$.Release.Name | quote }}
    helm.sh/chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    {{- toYaml $job.annotations | nindent 4 }}
spec:
  template:
    metadata:
      name: "{{$.Release.Name}}-migratation"
      labels:
        app.kubernetes.io/managed-by: {{$.Release.Service | quote }}
        app.kubernetes.io/instance: {{$.Release.Name | quote }}
        helm.sh/chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
        - name: {{ $job.name }}-migratation
          image: {{ $job.image}}
          command: {{- toYaml $job.command | nindent 12 }}
          args: {{- toYaml $job.args | nindent 12 }}
          envFrom:
  {{- toYaml $job.envFrom | nindent 10 }}
  {{- end }}
  {{- end}}
